spring:
  application:
    name: quasar-fire-operation
  datasource:
    url: jdbc:postgresql://10.1.24.70:3000/Transacciones
    username: comfenalco
    password: transacciones2020.
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          jdbc:
            lob:
              non_contextual_creation: true

server:
  port: 9500

