spring:
  application:
    name: quasar-fire-operation
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: quasar
      port: 27017
      host: localhost

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  packagesToScan: co.com.mercadolibre.quasarfireoperation.controller


server:
  port: 9500

